spring:
    datasource:
      url: jdbc:mysql://localhost:3306/jpa?characterEncoding=utf8
      username: root
      password: a068558a
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
          hibernate:
              dialect:





